// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type SupabaseClientType = ReturnType<typeof createClient<Database>>;

function createMockSupabaseClient(): SupabaseClientType {
  const subscription = { unsubscribe: () => {} };

  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription } } as any),
      getSession: async () => ({ data: { session: null }, error: null } as any),
      signOut: async () => ({ error: null } as any),
    },
    from: () => ({
      select: () => ({
        eq: () => ({
          single: async () => ({ data: null, error: null }),
        }),
      }),
      insert: async () => ({ data: null, error: null }),
    }),
    rpc: async () => ({ data: null, error: null } as any),
    functions: {
      invoke: async () => ({ data: null, error: null } as any),
    },
  } as any;
}

export const supabase: SupabaseClientType =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : (console.warn(
        "Supabase env vars are missing (VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY). Auth features are disabled until they are configured.",
      ),
      createMockSupabaseClient());